# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e0fad8c90a9ff97b6f0689f03c0a1640664d142f097fa1afb2f415670ea04b4701cbfc5bbd6537abc0ad1ac186ac1091939c65ff75f685616579cdfaf032bba

test:
  secret_key_base: e693587af33fb9a8269110693826543bcf415b73f27849fdf5dacde37b86cddd8b84eda378f8477b8a71886a41b69a3fee772870adcb5b778e68f6a1e816ed5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
